---

name: deploy-openedx-vars
on: [push]
jobs:
  deploy-openedx-vars:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout openedx-actions-demo repo"
        uses: actions/checkout@v2
      - name: "Install requiernments and bootstrap ansible"
        shell: bash
        run: |
          chmod +x ./bootstrap-ansible.sh
          sh ./bootstrap-ansible.sh
      - name: "Install SSH Key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: "Set Known Hosts"
        shell: bash
        run: |
          ssh-keygen -R ${{ secrets.SSH_HOST }}
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: "Run ansible playbook to deploy new configuration variables"
        run: |
          ssh root@159.223.189.100 "echo connected to the openedx server"
          sudo /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook configuration/playbooks/openedx_native.yml -t edxapp_cfg -i ./inventory
          echo "Deployment complete"
      - name: "Restart Open edX services to apply changes"
        run: |
          ssh root@159.223.189.100 "sudo /edx/bin/supervisorctl restart all"
          echo "Restarted all the services"
