---

name: deploy-openedx-vars
on: [push]
env:
  SSH_KEY: ${{ secrets.SSH_KEY }}
jobs:
  deploy-openedx-vars:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout openedx-actions-demo repo"
        uses: actions/checkout@v2
      - name: "Install requiernments and bootstrap ansible"
        shell: bash
        run: |
          chmod +x ./bootstrap-ansible.sh
          sh ./bootstrap-ansible.sh
      - name: "Run ansible playbook to deploy new configuration variables"
        run: |
          sudo /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook ./openedx_native.yml -i ~/inventory --private-key $SSH_KEY
          echo "Deployment complete"
      - name: "Restart Open edX services to apply changes"
        run: |
          ssh -o StrictHostKeyChecking=no 159.223.189.100
          ssh root@159.223.189.100 "sudo /edx/bin/supervisorctl restart all"
          echo "Restarted all the services"

